<?php

return [
  'standard' => [
    'label' => 'Basic Verified',
    'badge_label' => 'Verified Resort',
    'description' => 'Standard verification listing with scam-protected online bookings. Perfect for small resorts getting started.',
    'max_rooms' => 10,
    'monthly_price_php' => 0,
    'listing_priority' => 0,
    'features' => [
      'pms',
      'calendar',
      'booking_site',
      'notifications',
      'guest_dashboard',
      'reservation_management',
      'online_booking',
      'payment_methods',
      'verified_listing',
    ],
    'feature_labels' => [
      'Verified resort listing on Anti-ScamPH',
      'Up to 10 active rooms',
      'Online booking & reservation management',
      'Guest dashboard & notifications',
      'Payment method integration',
      'Calendar & availability management',
      'Anti-ScamPH verification badge',
      'Scam protection for guests',
    ],
  ],
  'business_pro' => [
    'label' => 'Business Pro Verified',
    'badge_label' => 'Premium Verified Resort',
    'description' => 'Priority visibility, advanced analytics, and the gold Business Pro badge — the highest trust signal on Anti-ScamPH.',
    'max_rooms' => 20,
    'monthly_price_php' => 1000,
    'listing_priority' => 100,
    'features' => [
      'analytics',
      'revenue_reports',
      'guest_traffic_analytics',
      'conversion_reports',
      'video_embed',
      'priority_listing',
      'downloadable_reports',
      'priority_support',
      'reward_growth_program',
      'business_insights',
    ],
    'feature_labels' => [
      'Everything in Basic Verified, plus:',
      'Up to 20 active rooms',
      'Priority listing in search results',
      'Video embed on landing page',
      'Analytics & revenue reports',
      'Guest traffic & conversion insights',
      'Downloadable business reports',
      'Priority support channel',
      'Reward growth program access',
      'Business Pro verified gold badge',
    ],
  ],
  'enterprise' => [
    'label' => 'Enterprise',
    'badge_label' => 'Enterprise Resort',
    'description' => 'Custom enterprise solution for large resort chains.',
    'max_rooms' => 50,
    'monthly_price_php' => 0,
    'listing_priority' => 200,
    'features' => [],
    'feature_labels' => [],
  ],
];
